model_name_or_path: ./models/Qwen2.5-1.5B-Instruct
train_data_path: ./data/kto/test_kto.json
output_dir: ./save_models/kto/Qwen2.5-1.5B-Instruct
torch_dtype: float16
device_map: auto
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
do_train: true
num_train_epochs: 3
# save_strategy: epoch
save_steps: 102
learning_rate: 5.0e-4
optim: adamw_torch
weight_decay: 0.0
fp16: true
max_length: 1024
max_grad_norm: 1.0
logging_steps: 10
preprocessing_num_workers: 16
lr_scheduler_type: cosine
trust_remote_code: true
remove_unused_columns: false
loss_type: kto
deepspeed: ./ds_config/ds_z3_config.json