model_name_or_path: ./models/Skywork-Reward-V2-Qwen3-0.6B
train_data_path: ./data/rm
output_dir: ./save_models/rm/Skywork-Reward-V2-Qwen3-0.6B
device_map: auto
max_length: 512
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
do_train: true
num_train_epochs: 3
# save_strategy: epoch
save_steps: 102
learning_rate: 1.0e-5
optim: adamw_torch
weight_decay: 0.0
fp16: true
max_grad_norm: 1.0
logging_steps: 10
preprocessing_num_workers: 16
lr_scheduler_type: cosine
trust_remote_code: true
# deepspeed: ./ds_config/ds_z3_config.json